#!/usr/bin/env python3
"""Relay stdin/stdout to a TCP socket (MCP bridge on host)."""
import os
import select
import socket
import sys

BUFSIZE = 65536

name = sys.argv[1].upper().replace("-", "_")
host = os.environ["MCP_BRIDGE_HOST"]
port = int(os.environ[f"MCP_BRIDGE_PORT_{name}"])

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((host, port))
sock.setblocking(False)

stdin_fd = sys.stdin.buffer.fileno()
stdout = sys.stdout.buffer

try:
    while True:
        readable, _, _ = select.select([stdin_fd, sock], [], [])
        for fd in readable:
            if fd is sock:
                data = sock.recv(BUFSIZE)
                if not data:
                    sys.exit(0)
                stdout.write(data)
                stdout.flush()
            else:
                data = os.read(stdin_fd, BUFSIZE)
                if not data:
                    sys.exit(0)
                sock.sendall(data)
except (BrokenPipeError, ConnectionResetError, OSError):
    pass
finally:
    sock.close()
